### PR TITLE
gdb: Conditionally provide gdbserver

### PR DESCRIPTION
**Pull request by drewmoseley**
Signed-off-by: Drew Moseley <drew_moseley@mentor.com>

### CODE REVIEW

**Comment by drewmoseley** [comment]
@kergoth I'm not sure if this is the right fix or not but I was getting multiple providers for gdbserver with the Cedar-based AMD builds when enabling tools-debug in my config.  Does this look reasonable or can you suggest a better approach?

Note that this PR is specifically against master.  Should it also be done against cedar?

**Comment by Noor-Ahsan** [comment]
@drewmoseley  Looks good to me. Another option might be we remove gdb from packagegroup-core-tools-debug in bbappend in case we dont need gdb on target.

**Comment by drewmoseley** [comment]
I'm getting an additional build issue here.
> The recipe gdbserver-external is trying to install files into a shared area when those files already exist.
I'm continuing to dig.

**Comment by drewmoseley** [comment]
@Noor-Ahsan @kergoth I added https://github.com/drewmoseley/meta-sourcery/commit/e2153741125e90bb21a8c88906fa0ada9c6ee88a to deal with the error resulting from files that were being populated by multiple packages.  I'm not sure if that's the right solution or not but it does at least silence the warnings.

**Comment by Noor-Ahsan** [comment]
@I'll let @kergoth  comment on it.

**Comment by drewmoseley** [comment]
I am adding a few more commits to remove some extra files that showed up in the MEL Commercial config.

**Comment by drewmoseley** [comment]
@kergoth this warning is triggered by a build using TCMODE=external and including tools-debug in EXTRA_IMAGE_FEATURES.  Would a reasonable solution be do conditionally set PREFERRED_PROVIDER_gdbserver in the meta-sourcery layer if tools-debug is included?

Or would it be better to somehow conditionalize it on whether gdb was set to be built or not?

**Comment by drewmoseley** [comment]
@kergoth ping

**Comment by kergoth** [comment]
[**@drewmoseley**](https://github.com/drewmoseley) commented on [Dec 6, 2015, 2:40 PM MST](https://github.com/MentorEmbedded/meta-sourcery/pull/110#issuecomment-162349983 "2015-12-06T21:40:15Z - Replied by Github Comment Enhancer"):
> @kergoth this warning is triggered by a build using TCMODE=external and including tools-debug in EXTRA_IMAGE_FEATURES.  Would a reasonable solution be do conditionally set PREFERRED_PROVIDER_gdbserver in the meta-sourcery layer if tools-debug is included?

That would work for the EXTRA_IMAGE_FEATURES case, which I guess would be better than nothing, but it'd be less than useless if someone adds it to IMAGE_FEATURES in an image recipe.

> Or would it be better to somehow conditionalize it on whether gdb was set to be built or not?

There's no way to conditionalize it in that way, that information isn't available. Also, gdb could have been built in an entirely different bitbake execution.

Personally, I'm tempted to say we just default gdbserver-external to not be used by default, if someone wants gdbserver, they can build gdb, and we sidestep this issue. It'd affect build times, but.. we have very few options here. Either we change that default, or we document that the user needs to set the preference if they want to build gdb.

**Comment by drewmoseley** [comment]
I'm still testing but it looks like this current version works by simply setting the PREFERRED_PROVIDER to gdb.

**Comment by drewmoseley** [comment]
My testing has completed and it looks like gdbserver gets properly installed from the gdb package in the MEL configurations that I built.  I'm also able to build with the tools-debug included without errors.

@kergoth @Noor-Ahsan please review.

**Comment by kergoth** [comment]
The diff looks fine, but both commits are missing commit message bodies describing the *why* behind the change. Lacking the context from this pull request, it'd be difficult to determine the reasoning when examining the git log years from now.

**Comment by drewmoseley** [comment]
Updated with better commit messages.

**Comment by kergoth** [comment]
Thanks, looks good to me.

**Pull request merged**
