### PR TITLE
adds architecture link in ADE Target Sysroot

### PR DESCRIPTION
**Pull request by adnan-ali1**
The Earlier PR has some extra useless commits which are not required. This has only the required changes in 1 commit

Signed-off-by: adnan-ali1 <adnan_ali@mentor.com>

### CODE REVIEW

**Comment by adnan-ali1** [comment]
The previous PR is at https://github.com/MentorEmbedded/meta-sourcery/pull/74

**Comment by kergoth** [comment]
I'm not merging this as is, because the git commit message does not comply with our conventions (wrong tense, not prefixed with the package), and the subject references the ADE, even though the ADE isn't the only thing affected by this. I'll fix up the commit message myself for now to reduce further back-and-forth on the pull request and push that.

**Comment by kergoth** [comment]
Also, your name is wrong in your git configuration. 'adnan-ali1' is not appropriate for the user.name / GIT_AUTHOR_NAME/GIT_COMMITTER_NAME. Use your full name there.

**Comment by kergoth** [comment]
Pushed, see https://github.com/MentorEmbedded/meta-sourcery/commit/3f10799bf77297de4088df40b67a71250e908d77.

**Pull request closed without merging**
