### PR TITLE
glibc-sourcery: align with the CB build

### PR DESCRIPTION
**Pull request by kergoth**

### CODE REVIEW

**Comment by mdurnev** [comment]
@kergoth, are you going to close https://github.com/MentorEmbedded/meta-sourcery/pull/220 ?

**Comment by mdurnev** [comment]
CUSTOMER ISSUE ID: TBD
MGC ISSUE ID: ADIT-80
SUMMARY: Rebuild glibc from sources
DESCRIPTION: Rebuild glibc from sources to binary as close to CB 11 as possible
RESOLUTION: Align with the CB build.
DEPENDENCIES: https://github.com/MentorEmbedded/adit-custom/pull/918 , https://github.com/MentorEmbedded/meta-sourcery/pull/220
LICENSE: MIT
TEST SUMMARY: Build test with TCMODE = "external-sourcery" (current COS default) and with TCMODE = "external-sourcery-rebuild-libc" (we will use it for CVE fixes in glibc) in local.conf.
KNOWN LIMITATIONS: None
SOURCES: None

**Comment by Noor-Ahsan** [comment]
@mdurnev  kindly provide your approval to the PR.

**Comment by mdurnev** [comment]
@Noor-Ahsan, if you practice basing one PR on another open PR then I am Ok. But I personally prefer independent PRs.

Before I proceed with approval of the PR I need feedback from @kergoth on my request about build flag review (see in the ticket).

**Comment by kergoth** [comment]
[**@mdurnev**](https://github.com/mdurnev) commented on [Jan 29, 2021, 12:54 AM MST](https://github.com/MentorEmbedded/meta-sourcery/pull/224#issuecomment-769642436 "2021-01-29T07:54:20Z - Replied by Github Reply Comments"):
> @Noor-Ahsan, if you practice basing one PR on another open PR then I am Ok. But I personally prefer independent PRs.
> 
> Before I proceed with approval of the PR I need feedback from @kergoth on my request about build flag review (see in the ticket).

I'll update to remove the other pr's pull requests. We generally make them independent where possible, but it's not always possible due to conflicts. Getting the compiler options from the log now.

**Comment by kergoth** [comment]
[**@kergoth**](https://github.com/kergoth) commented on [Jan 29, 2021, 10:21 AM MST](https://github.com/MentorEmbedded/meta-sourcery/pull/224#issuecomment-769937838 "2021-01-29T17:21:50Z - Replied by Github Reply Comments"):
> [**@mdurnev**](https://github.com/mdurnev) commented on [Jan 29, 2021, 12:54 AM MST](https://github.com/MentorEmbedded/meta-sourcery/pull/224#issuecomment-769642436 "2021-01-29T07:54:20Z - Replied by Github Reply Comments"):
> > @Noor-Ahsan, if you practice basing one PR on another open PR then I am Ok. But I personally prefer independent PRs.
> > 
> > Before I proceed with approval of the PR I need feedback from @kergoth on my request about build flag review (see in the ticket).
> 
> I'll update to remove the other pr's pull requests. We generally make them independent where possible, but it's not always possible due to conflicts. Getting the compiler options from the log now.

Rebased to only contain the changes for this.

**Review by mdurnev — APPROVED** [review]

**Pull request merged**
