### PR TITLE
tcmode: set EXTERNAL_TOOLCHAIN from CODEBENCH_PATH for multilibs

### PR DESCRIPTION
**Pull request by kergoth**

### CODE REVIEW

**Comment by kergoth** [comment]
This sets `EXTERNAL_TOOLCHAIN`, `EXTERNAL_TOOLCHAIN_virtclass-multilib-lib32`, etc, and the same for `EXTERNAL_TARGET_SYS`.

**Comment by kergoth** [comment]
I already pushed the depends bugfix to meta-external-toolchain (which reminds me, need to create that on github too for easier contributions.

**Comment by chombourger** [comment]
do we want to add the details you added as PR comments into the git commit log?

**Comment by kergoth** [comment]
Updated. Good idea, thanks.

**Comment by Noor-Ahsan** [comment]
>I already pushed the depends bugfix to meta-external-toolchain (which reminds me, need to create that on github too for easier contributions.
need manifest PR to get these Fixes.

**Comment by Noor-Ahsan** [comment]
If we have only set EXTERNAL_TOOLCHAIN var will this work?

**Comment by Noor-Ahsan** [comment]
glibc-sourcery is failing on my side with on ultrazed with following error

 error: /data/noor/mel/releases/builds/elm/main/build_ultrazed/tmp/work/armv7vehf-neon-vfpv4-melmllib32-linux-gnueabi/lib32-glibc-sourcery/2.27-2018.05-10-r0/build-arm-melmllib32-linux-gnueabi/elf/librtld.map.o uses VFP register arguments, /data/common/toolchains/2018-07_arm/toolchains/arm-none-linux-gnueabi.2018.05/bin/../lib/gcc/arm-none-linux-gnueabi/7.3.1/libgcc.a(_udivmoddi4.o) does not
| /data/common/toolchains/2018-07_arm/toolchains/arm-none-linux-gnueabi.2018.05/bin/../lib/gcc/arm-none-linux-gnueabi/7.3.1/../../../../arm-none-linux-gnueabi/bin/ld: failed to merge target specific data of file /data/common/toolchains/2018-07_arm/toolchains/arm-none-linux-gnueabi.2018.05/bin/../lib/gcc/arm-none-linux-gnueabi/7.3.1/libgcc.a(_udivmoddi4.o)

I added this in ultrazed machine
require conf/multilib.conf
MULTILIBS = "multilib:lib32"
DEFAULTTUNE_virtclass-multilib-lib32 ?= "armv7vethf-neon-vfpv4"
IMAGE_INSTALL_append = " lib32-glib-2.0"
Let me know if something else needs to be added.

**Comment by Noor-Ahsan** [comment]
I noticed one thing when I built with internel toolchain with same multilib I get these dependencies
"development-image" -> "lib32-binutils-cross-arm"
"development-image" -> "lib32-gcc-cross-arm"
"development-image" -> "lib32-gcc-cross-initial-arm"
"development-image" -> "lib32-gcc-runtime"
"development-image" -> "lib32-glibc"
"development-image" -> "lib32-glibc-initial"
"development-image" -> "lib32-libgcc"
"development-image" -> "lib32-libgcc-initial"
"development-image" -> "lib32-linux-libc-headers"

I don't get lib32-bash in graph.
when I use sorucery toolchain I get these dependencies

"development-image" -> "lib32-base-files"
"development-image" -> "lib32-bash"
"development-image" -> "lib32-binutils-external-cross-arm"
"development-image" -> "lib32-chkconfig-alternatives"
"development-image" -> "lib32-gcc-external-cross-arm"
"development-image" -> "lib32-gcc-runtime-external"
"development-image" -> "lib32-glibc-locale"
"development-image" -> "lib32-glibc-sourcery"
"development-image" -> "lib32-libgcc-external"
"development-image" -> "lib32-libtool-cross"
"development-image" -> "lib32-linux-libc-headers-external"
"development-image" -> "lib32-ncurses"
see there are some extra lib32 packages in sourcery config. lib32-bash failed in our config as mentioned earlier.

**Comment by kergoth** [comment]
It's likely bash is being pulled in by one of the glibc recipes pulling it in rather than patching out the dependency, we can improve that further. The bash thing I did hit as well but forgot I had the workaround locally. I'll update the pull req.

**Comment by Noor-Ahsan** [comment]
my build went fine after new fixes. I will test the output. We need to decide when and where we need to merge as we not planning it to make part of elm main release atm.

**Comment by kergoth** [comment]
Unless the user enables multilibs, this pull req will have no effect on their build at all. So depends on how paranoid you want to be about the change.

**Comment by Noor-Ahsan** [comment]
yeah I was thinking about this while commenting :) that untill I add multilib support in machine this will not have any impact.

**Pull request merged**
