### PR TITLE
Migrate to oe-based toolchain

### PR DESCRIPTION
**Pull request by kergoth**

### CODE REVIEW

**Comment by kergoth** [comment]
This will depend upon the meta-external-toolchain changes.

**Comment by Noor-Ahsan** [comment]
@kergoth where tcmode-external-codebench-yocto.inc will be included?

**Comment by kergoth** [comment]
[**@Noor-Ahsan**](https://github.com/Noor-Ahsan) commented on [Jul 8, 2020, 9:43 AM MST](https://github.com/MentorEmbedded/meta-sourcery/pull/204#issuecomment-655631831 "2020-07-08T16:43:46Z - Replied by Github Reply Comments"):
> @kergoth where tcmode-external-codebench-yocto.inc will be included?

TCMODE controls that, we set a default value in mel.conf. My intention is to rework the pull req as I mentioned on the call yesterday to alter the existing tcmode rather than adding a new one, since we no longer need compatibility with the old toolchain on the affected branches. Expect an update to this today.

**Comment by kergoth** [comment]
@Noor-Ahsan updated to alter the existing tcmode(s) instead of adding a new one.

**Pull request merged**
