### PR TITLE
adds architecture link in ADE Target Sysroot

### PR DESCRIPTION
**Pull request by adnan-ali1**
The Earlier PR has some extra useless commits which are not required. This has only the required changes in 1 commit

Signed-off-by: adnan-ali1 <adnan_ali@mentor.com>

### CODE REVIEW

**Comment by adnan-ali1** [comment]
The previous PR is at https://github.com/MentorEmbedded/meta-sourcery/pull/74

**Comment by adnan-ali1** [comment]
A mistake in the commit message has been found. The link was added to FILES_${PN}-dev instead of FILES_glibc-multilib-link. So closing this PR and creating a new one

**Comment by kergoth** [comment]
You don't need to resubmit a new pull request to get every change in. You can just push the changes to the existing branch and the existing pull request will update.

**Comment by adnan-ali1** [comment]
Thank you Chris for the helpful information. I'll keep that in mind the next time

**Pull request closed without merging**
