### PR TITLE
glibc-sourcery: align sources with the CB build

### PR DESCRIPTION
**Pull request by kergoth**
JIRA: SB-16857

Signed-off-by: Christopher Larson <chris_larson@mentor.com>

### CODE REVIEW

**Comment by kergoth** [comment]
@jeremy-robinson Do you know who the best reviewers would be on this?

**Comment by Noor-Ahsan** [comment]
From Paul Carroll

https://jira.alm.mentorg.com/browse/SB-16857?focusedCommentId=775696&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-775696

**Comment by Noor-Ahsan** [comment]
@kergoth can you add more info in git commit from which repo and hash you generated the diff so that we may come back to it later if we need it. That will be helpful information although we have some info in jira but I think we should have something in git commit summary also

**Comment by kergoth** [comment]
We don't want this at all, it's not needed to align with the tag they're using.

**Pull request closed without merging**
